// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "nav": {
    "home": "Home",
    "about": "About",
    "howItWorks": "How It Works",
    "templates": "Templates",
    "pricing": "Pricing",
    "blog": "Blog",
    "contact": "Contact",
    "events": "Events",
    "categories": "Categories"
  },
  "auth": {
    "login": "Log In",
    "getStarted": "Get Started"
  }
};
export default messages;